<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>$(NetRoslyn);net472</TargetFrameworks>
    <AutoGenerateAssemblyVersion>true</AutoGenerateAssemblyVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj" Private="true" />
    <ProjectReference Include="..\..\..\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj" Private="true" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SemanticSearch.BuildTask.UnitTests" />
  </ItemGroup>

  <Import Project="$(RepositoryEngineeringDir)targets\BuildTask.props" />
  <Import Project="..\..\..\Dependencies\Contracts\Microsoft.CodeAnalysis.Contracts.projitems" Label="Shared" />
</Project>
