// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.CodeStyle;

namespace Microsoft.CodeAnalysis.CSharp.Formatting
{
    internal record CSharpFormatterOptions(
        bool AllowDisjointSpanMerging,
        bool AutoFormattingOnReturn,
        FormattingOptions.IndentStyle IndentStyle,
        string NewLine,
        int IndentationSize,
        int TabSize,
        bool UseTabs,
        bool SeparateImportDirectiveGroups,
        OperatorPlacementWhenWrappingPreference OperatorPlacementWhenWrapping,
        int PreferredWrappingColumn,
        bool SpacingAfterMethodDeclarationName,
        bool SpaceWithinMethodDeclarationParenthesis,
        bool SpaceBetweenEmptyMethodDeclarationParentheses,
        bool SpaceAfterMethodCallName,
        bool SpaceWithinMethodCallParentheses,
        bool SpaceBetweenEmptyMethodCallParentheses,
        bool SpaceAfterControlFlowStatementKeyword,
        bool SpaceWithinExpressionParentheses,
        bool SpaceWithinCastParentheses,
        bool SpaceWithinOtherParentheses,
        bool SpaceAfterCast,
        bool SpacesIgnoreAroundVariableDeclaration,
        bool SpaceBeforeOpenSquareBracket,
        bool SpaceBetweenEmptySquareBrackets,
        bool SpaceWithinSquareBrackets,
        bool SpaceAfterColonInBaseTypeDeclaration,
        bool SpaceAfterComma,
        bool SpaceAfterDot,
        bool SpaceAfterSemicolonsInForStatement,
        bool SpaceBeforeColonInBaseTypeDeclaration,
        bool SpaceBeforeComma,
        bool SpaceBeforeDot,
        bool SpaceBeforeSemicolonsInForStatement,
        BinaryOperatorSpacingOptions SpacingAroundBinaryOperator,
        bool IndentBraces,
        bool IndentBlock,
        bool IndentSwitchSection,
        bool IndentSwitchCaseSection,
        bool IndentSwitchCaseSectionWhenBlock,
        LabelPositionOptions LabelPositioning,
        bool WrappingPreserveSingleLine,
        bool WrappingKeepStatementsOnSingleLine,
        bool NewLinesForBracesInTypes,
        bool NewLinesForBracesInMethods,
        bool NewLinesForBracesInProperties,
        bool NewLinesForBracesInAccessors,
        bool NewLinesForBracesInAnonymousMethods,
        bool NewLinesForBracesInControlBlocks,
        bool NewLinesForBracesInAnonymousTypes,
        bool NewLinesForBracesInObjectCollectionArrayInitializers,
        bool NewLinesForBracesInLambdaExpressionBody,
        bool NewLineForElse,
        bool NewLineForCatch,
        bool NewLineForFinally,
        bool NewLineForMembersInObjectInit,
        bool NewLineForMembersInAnonymousTypes,
        bool NewLineForClausesInQuery) : FormatterOptions(
            AllowDisjointSpanMerging,
            AutoFormattingOnReturn,
            IndentStyle,
            NewLine,
            IndentationSize,
            TabSize,
            UseTabs,
            SeparateImportDirectiveGroups,
            OperatorPlacementWhenWrapping,
            PreferredWrappingColumn)
    {
        public static readonly CSharpFormatterOptions Default
            = new(
#if CODE_STYLE
                // Unused in code-style layer
                AllowDisjointSpanMerging: false,
                AutoFormattingOnReturn: false,
                IndentStyle: FormattingOptions.IndentStyle.None,
#else
                AllowDisjointSpanMerging: FormattingBehaviorOptions.AllowDisjointSpanMerging.DefaultValue,
                AutoFormattingOnReturn: FormattingBehaviorOptions.AutoFormattingOnReturn.DefaultValue,
                IndentStyle: FormattingBehaviorOptions.SmartIndent.DefaultValue,
#endif
                OperatorPlacementWhenWrapping: CodeStyleOptions2.OperatorPlacementWhenWrapping.DefaultValue,
                PreferredWrappingColumn: FormattingOptions2.PreferredWrappingColumn.DefaultValue,
                NewLine: FormattingOptions2.NewLine.DefaultValue,
                IndentationSize: FormattingOptions2.IndentationSize.DefaultValue,
                TabSize: FormattingOptions2.TabSize.DefaultValue,
                UseTabs: FormattingOptions2.UseTabs.DefaultValue,
                SeparateImportDirectiveGroups: GenerationOptions.SeparateImportDirectiveGroups.DefaultValue,
                SpacingAfterMethodDeclarationName: CSharpFormattingOptions2.SpacingAfterMethodDeclarationName.DefaultValue,
                SpaceWithinMethodDeclarationParenthesis: CSharpFormattingOptions2.SpaceWithinMethodDeclarationParenthesis.DefaultValue,
                SpaceBetweenEmptyMethodDeclarationParentheses: CSharpFormattingOptions2.SpaceBetweenEmptyMethodDeclarationParentheses.DefaultValue,
                SpaceAfterMethodCallName: CSharpFormattingOptions2.SpaceAfterMethodCallName.DefaultValue,
                SpaceWithinMethodCallParentheses: CSharpFormattingOptions2.SpaceWithinMethodCallParentheses.DefaultValue,
                SpaceBetweenEmptyMethodCallParentheses: CSharpFormattingOptions2.SpaceBetweenEmptyMethodCallParentheses.DefaultValue,
                SpaceAfterControlFlowStatementKeyword: CSharpFormattingOptions2.SpaceAfterControlFlowStatementKeyword.DefaultValue,
                SpaceWithinExpressionParentheses: CSharpFormattingOptions2.SpaceWithinExpressionParentheses.DefaultValue,
                SpaceWithinCastParentheses: CSharpFormattingOptions2.SpaceWithinCastParentheses.DefaultValue,
                SpaceWithinOtherParentheses: CSharpFormattingOptions2.SpaceWithinOtherParentheses.DefaultValue,
                SpaceAfterCast: CSharpFormattingOptions2.SpaceAfterCast.DefaultValue,
                SpacesIgnoreAroundVariableDeclaration: CSharpFormattingOptions2.SpacesIgnoreAroundVariableDeclaration.DefaultValue,
                SpaceBeforeOpenSquareBracket: CSharpFormattingOptions2.SpaceBeforeOpenSquareBracket.DefaultValue,
                SpaceBetweenEmptySquareBrackets: CSharpFormattingOptions2.SpaceBetweenEmptySquareBrackets.DefaultValue,
                SpaceWithinSquareBrackets: CSharpFormattingOptions2.SpaceWithinSquareBrackets.DefaultValue,
                SpaceAfterColonInBaseTypeDeclaration: CSharpFormattingOptions2.SpaceAfterColonInBaseTypeDeclaration.DefaultValue,
                SpaceAfterComma: CSharpFormattingOptions2.SpaceAfterComma.DefaultValue,
                SpaceAfterDot: CSharpFormattingOptions2.SpaceAfterDot.DefaultValue,
                SpaceAfterSemicolonsInForStatement: CSharpFormattingOptions2.SpaceAfterSemicolonsInForStatement.DefaultValue,
                SpaceBeforeColonInBaseTypeDeclaration: CSharpFormattingOptions2.SpaceBeforeColonInBaseTypeDeclaration.DefaultValue,
                SpaceBeforeComma: CSharpFormattingOptions2.SpaceBeforeComma.DefaultValue,
                SpaceBeforeDot: CSharpFormattingOptions2.SpaceBeforeDot.DefaultValue,
                SpaceBeforeSemicolonsInForStatement: CSharpFormattingOptions2.SpaceBeforeSemicolonsInForStatement.DefaultValue,
                SpacingAroundBinaryOperator: CSharpFormattingOptions2.SpacingAroundBinaryOperator.DefaultValue,
                IndentBraces: CSharpFormattingOptions2.IndentBraces.DefaultValue,
                IndentBlock: CSharpFormattingOptions2.IndentBlock.DefaultValue,
                IndentSwitchSection: CSharpFormattingOptions2.IndentSwitchSection.DefaultValue,
                IndentSwitchCaseSection: CSharpFormattingOptions2.IndentSwitchCaseSection.DefaultValue,
                IndentSwitchCaseSectionWhenBlock: CSharpFormattingOptions2.IndentSwitchCaseSectionWhenBlock.DefaultValue,
                LabelPositioning: CSharpFormattingOptions2.LabelPositioning.DefaultValue,
                WrappingPreserveSingleLine: CSharpFormattingOptions2.WrappingPreserveSingleLine.DefaultValue,
                WrappingKeepStatementsOnSingleLine: CSharpFormattingOptions2.WrappingKeepStatementsOnSingleLine.DefaultValue,
                NewLinesForBracesInTypes: CSharpFormattingOptions2.NewLinesForBracesInTypes.DefaultValue,
                NewLinesForBracesInMethods: CSharpFormattingOptions2.NewLinesForBracesInMethods.DefaultValue,
                NewLinesForBracesInProperties: CSharpFormattingOptions2.NewLinesForBracesInProperties.DefaultValue,
                NewLinesForBracesInAccessors: CSharpFormattingOptions2.NewLinesForBracesInAccessors.DefaultValue,
                NewLinesForBracesInAnonymousMethods: CSharpFormattingOptions2.NewLinesForBracesInAnonymousMethods.DefaultValue,
                NewLinesForBracesInControlBlocks: CSharpFormattingOptions2.NewLinesForBracesInControlBlocks.DefaultValue,
                NewLinesForBracesInAnonymousTypes: CSharpFormattingOptions2.NewLinesForBracesInAnonymousTypes.DefaultValue,
                NewLinesForBracesInObjectCollectionArrayInitializers: CSharpFormattingOptions2.NewLinesForBracesInObjectCollectionArrayInitializers.DefaultValue,
                NewLinesForBracesInLambdaExpressionBody: CSharpFormattingOptions2.NewLinesForBracesInLambdaExpressionBody.DefaultValue,
                NewLineForElse: CSharpFormattingOptions2.NewLineForElse.DefaultValue,
                NewLineForCatch: CSharpFormattingOptions2.NewLineForCatch.DefaultValue,
                NewLineForFinally: CSharpFormattingOptions2.NewLineForFinally.DefaultValue,
                NewLineForMembersInObjectInit: CSharpFormattingOptions2.NewLineForMembersInObjectInit.DefaultValue,
                NewLineForMembersInAnonymousTypes: CSharpFormattingOptions2.NewLineForMembersInAnonymousTypes.DefaultValue,
                NewLineForClausesInQuery: CSharpFormattingOptions2.NewLineForClausesInQuery.DefaultValue);

        public static FormatterOptions From(AnalyzerConfigOptions options)
            => new CSharpFormatterOptions(
#if CODE_STYLE
                // Unused in code-style layer
                AllowDisjointSpanMerging: false,
                AutoFormattingOnReturn: false,
                IndentStyle: FormattingOptions.IndentStyle.None,
#else
                AllowDisjointSpanMerging: options.GetOption(FormattingBehaviorOptions.AllowDisjointSpanMerging),
                AutoFormattingOnReturn: options.GetOption(FormattingBehaviorOptions.AutoFormattingOnReturn),
                IndentStyle: options.GetOption(FormattingBehaviorOptions.SmartIndent),
#endif
                NewLine: options.GetOption(FormattingOptions2.NewLine),
                IndentationSize: options.GetOption(FormattingOptions2.IndentationSize),
                TabSize: options.GetOption(FormattingOptions2.TabSize),
                UseTabs: options.GetOption(FormattingOptions2.UseTabs),
                SeparateImportDirectiveGroups: options.GetOption(GenerationOptions.SeparateImportDirectiveGroups),
                OperatorPlacementWhenWrapping: options.GetOption(CodeStyleOptions2.OperatorPlacementWhenWrapping),
                PreferredWrappingColumn: options.GetOption(FormattingOptions2.PreferredWrappingColumn),
                SpacingAfterMethodDeclarationName: options.GetOption(CSharpFormattingOptions2.SpacingAfterMethodDeclarationName),
                SpaceWithinMethodDeclarationParenthesis: options.GetOption(CSharpFormattingOptions2.SpaceWithinMethodDeclarationParenthesis),
                SpaceBetweenEmptyMethodDeclarationParentheses: options.GetOption(CSharpFormattingOptions2.SpaceBetweenEmptyMethodDeclarationParentheses),
                SpaceAfterMethodCallName: options.GetOption(CSharpFormattingOptions2.SpaceAfterMethodCallName),
                SpaceWithinMethodCallParentheses: options.GetOption(CSharpFormattingOptions2.SpaceWithinMethodCallParentheses),
                SpaceBetweenEmptyMethodCallParentheses: options.GetOption(CSharpFormattingOptions2.SpaceBetweenEmptyMethodCallParentheses),
                SpaceAfterControlFlowStatementKeyword: options.GetOption(CSharpFormattingOptions2.SpaceAfterControlFlowStatementKeyword),
                SpaceWithinExpressionParentheses: options.GetOption(CSharpFormattingOptions2.SpaceWithinExpressionParentheses),
                SpaceWithinCastParentheses: options.GetOption(CSharpFormattingOptions2.SpaceWithinCastParentheses),
                SpaceWithinOtherParentheses: options.GetOption(CSharpFormattingOptions2.SpaceWithinOtherParentheses),
                SpaceAfterCast: options.GetOption(CSharpFormattingOptions2.SpaceAfterCast),
                SpacesIgnoreAroundVariableDeclaration: options.GetOption(CSharpFormattingOptions2.SpacesIgnoreAroundVariableDeclaration),
                SpaceBeforeOpenSquareBracket: options.GetOption(CSharpFormattingOptions2.SpaceBeforeOpenSquareBracket),
                SpaceBetweenEmptySquareBrackets: options.GetOption(CSharpFormattingOptions2.SpaceBetweenEmptySquareBrackets),
                SpaceWithinSquareBrackets: options.GetOption(CSharpFormattingOptions2.SpaceWithinSquareBrackets),
                SpaceAfterColonInBaseTypeDeclaration: options.GetOption(CSharpFormattingOptions2.SpaceAfterColonInBaseTypeDeclaration),
                SpaceAfterComma: options.GetOption(CSharpFormattingOptions2.SpaceAfterComma),
                SpaceAfterDot: options.GetOption(CSharpFormattingOptions2.SpaceAfterDot),
                SpaceAfterSemicolonsInForStatement: options.GetOption(CSharpFormattingOptions2.SpaceAfterSemicolonsInForStatement),
                SpaceBeforeColonInBaseTypeDeclaration: options.GetOption(CSharpFormattingOptions2.SpaceBeforeColonInBaseTypeDeclaration),
                SpaceBeforeComma: options.GetOption(CSharpFormattingOptions2.SpaceBeforeComma),
                SpaceBeforeDot: options.GetOption(CSharpFormattingOptions2.SpaceBeforeDot),
                SpaceBeforeSemicolonsInForStatement: options.GetOption(CSharpFormattingOptions2.SpaceBeforeSemicolonsInForStatement),
                SpacingAroundBinaryOperator: options.GetOption(CSharpFormattingOptions2.SpacingAroundBinaryOperator),
                IndentBraces: options.GetOption(CSharpFormattingOptions2.IndentBraces),
                IndentBlock: options.GetOption(CSharpFormattingOptions2.IndentBlock),
                IndentSwitchSection: options.GetOption(CSharpFormattingOptions2.IndentSwitchSection),
                IndentSwitchCaseSection: options.GetOption(CSharpFormattingOptions2.IndentSwitchCaseSection),
                IndentSwitchCaseSectionWhenBlock: options.GetOption(CSharpFormattingOptions2.IndentSwitchCaseSectionWhenBlock),
                LabelPositioning: options.GetOption(CSharpFormattingOptions2.LabelPositioning),
                WrappingPreserveSingleLine: options.GetOption(CSharpFormattingOptions2.WrappingPreserveSingleLine),
                WrappingKeepStatementsOnSingleLine: options.GetOption(CSharpFormattingOptions2.WrappingKeepStatementsOnSingleLine),
                NewLinesForBracesInTypes: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInTypes),
                NewLinesForBracesInMethods: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInMethods),
                NewLinesForBracesInProperties: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInProperties),
                NewLinesForBracesInAccessors: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInAccessors),
                NewLinesForBracesInAnonymousMethods: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInAnonymousMethods),
                NewLinesForBracesInControlBlocks: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInControlBlocks),
                NewLinesForBracesInAnonymousTypes: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInAnonymousTypes),
                NewLinesForBracesInObjectCollectionArrayInitializers: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInObjectCollectionArrayInitializers),
                NewLinesForBracesInLambdaExpressionBody: options.GetOption(CSharpFormattingOptions2.NewLinesForBracesInLambdaExpressionBody),
                NewLineForElse: options.GetOption(CSharpFormattingOptions2.NewLineForElse),
                NewLineForCatch: options.GetOption(CSharpFormattingOptions2.NewLineForCatch),
                NewLineForFinally: options.GetOption(CSharpFormattingOptions2.NewLineForFinally),
                NewLineForMembersInObjectInit: options.GetOption(CSharpFormattingOptions2.NewLineForMembersInObjectInit),
                NewLineForMembersInAnonymousTypes: options.GetOption(CSharpFormattingOptions2.NewLineForMembersInAnonymousTypes),
                NewLineForClausesInQuery: options.GetOption(CSharpFormattingOptions2.NewLineForClausesInQuery)
            );
    }
}
